// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortfolioTracker.Infrastructure.Data;

#nullable disable

namespace PortfolioTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514222319_SeedAssets")]
    partial class SeedAssets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortfolioTracker.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Amerikan Doları",
                            Symbol = "USD",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Euro",
                            Symbol = "EUR",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "İngiliz Sterlini",
                            Symbol = "GBP",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "İsviçre Frangı",
                            Symbol = "CHF",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Japon Yeni",
                            Symbol = "JPY",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bitcoin",
                            Symbol = "BTC",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ethereum",
                            Symbol = "ETH",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "BNB",
                            Symbol = "BNB",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Solana",
                            Symbol = "SOL",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "XRP",
                            Symbol = "XRP",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Altın (gram)",
                            Symbol = "XAU",
                            Type = 3
                        },
                        new
                        {
                            Id = 12,
                            Name = "Gümüş (gram)",
                            Symbol = "XAG",
                            Type = 3
                        },
                        new
                        {
                            Id = 13,
                            Name = "Türk Hava Yolları",
                            Symbol = "THYAO",
                            Type = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "Garanti BBVA",
                            Symbol = "GARAN",
                            Type = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "Aselsan",
                            Symbol = "ASELS",
                            Type = 2
                        },
                        new
                        {
                            Id = 16,
                            Name = "Ereğli Demir Çelik",
                            Symbol = "EREGL",
                            Type = 2
                        },
                        new
                        {
                            Id = 17,
                            Name = "Şişe Cam",
                            Symbol = "SISE",
                            Type = 2
                        });
                });

            modelBuilder.Entity("PortfolioTracker.Domain.Entities.CurrencyPrice", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AssetId");

                    b.ToTable("CurrencyPrices");
                });

            modelBuilder.Entity("PortfolioTracker.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PortfolioTracker.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PortfolioTracker.Domain.Entities.UserPortfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("AssetId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPortfolios");
                });

            modelBuilder.Entity("PortfolioTracker.Domain.Entities.CurrencyPrice", b =>
                {
                    b.HasOne("PortfolioTracker.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("PortfolioTracker.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("PortfolioTracker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PortfolioTracker.Domain.Entities.UserPortfolio", b =>
                {
                    b.HasOne("PortfolioTracker.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortfolioTracker.Domain.Entities.User", "User")
                        .WithMany("Portfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PortfolioTracker.Domain.Entities.User", b =>
                {
                    b.Navigation("Portfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
